-- HashPass Moments foundation: organizer-funded proof-of-attendance collectibles.
create table if not exists collectible_collections (
  id uuid primary key default gen_random_uuid(), source text not null, event_id text not null, collectible_type text not null default 'proof_of_attendance', name text not null, description text not null, artwork_uri text not null, metadata jsonb not null default '{}'::jsonb, issuer_name text not null default 'HashPass', chain_family text not null default 'algorand', network text, contract_or_app_id text, standard text, max_supply integer, claim_start timestamptz, claim_end timestamptz, status text not null default 'draft', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(event_id, collectible_type));
create table if not exists attendance_credentials (
  id uuid primary key default gen_random_uuid(), event_id text not null, user_id uuid not null, role text not null default 'attendee', attendance_status text not null, verification_method text not null, verification_reference text, verified_by uuid, verified_at timestamptz not null default now(), metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create unique index if not exists attendance_credentials_unique_verified_reference on attendance_credentials(event_id, user_id, role, verification_method, coalesce(verification_reference,'')) where attendance_status = 'verified';
create table if not exists collectible_items (
  id uuid primary key default gen_random_uuid(), collection_id uuid not null references collectible_collections(id) on delete restrict, user_id uuid, source_identifier text not null unique, token_id text, holder_subject text not null, owner_address text, metadata_uri text, image_uri text, proof_digest text not null, onchain_status text not null default 'claimable_onchain', transaction_id text, issued_at timestamptz not null default now(), claimed_at timestamptz, revoked_at timestamptz, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(collection_id, user_id));
create table if not exists moment_claims (
  id uuid primary key default gen_random_uuid(), collection_id uuid not null references collectible_collections(id), user_id uuid not null, attendance_credential_id uuid not null references attendance_credentials(id), collectible_item_id uuid references collectible_items(id), idempotency_key text not null unique, claim_status text not null, claim_channel text not null default 'wallet', wallet_address text, transaction_id text, claimed_at timestamptz, failure_code text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(collection_id, user_id));
create table if not exists linked_wallets (id uuid primary key default gen_random_uuid(), user_id uuid not null, chain_family text not null, address text not null, verification_method text not null, verification_signature_hash text not null, verified_at timestamptz not null default now(), last_ownership_refresh timestamptz, revoked_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id, chain_family, lower(address)));
create table if not exists legacy_collectibles (id uuid primary key default gen_random_uuid(), user_id uuid not null, source text not null, chain_id integer not null, contract_address text not null, token_id text not null, source_event_id text, owner_address text not null, metadata_uri text, image_uri text, normalized_metadata jsonb not null default '{}'::jsonb, ownership_status text not null, verified_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id, source, chain_id, lower(contract_address), token_id));
create table if not exists sponsored_issuance (id uuid primary key default gen_random_uuid(), event_id text not null, sponsor text not null, purchased_capacity integer not null, used_capacity integer not null default 0, payment_network text not null, payment_transaction text not null unique, amount numeric not null, status text not null, created_at timestamptz not null default now());
create index if not exists collectible_collections_event_idx on collectible_collections(event_id);
create index if not exists collectible_items_proof_idx on collectible_items(proof_digest);
create index if not exists collectible_items_tx_idx on collectible_items(transaction_id);
create index if not exists moment_claims_status_idx on moment_claims(claim_status);
create index if not exists moment_claims_user_idx on moment_claims(user_id);
create index if not exists linked_wallets_address_idx on linked_wallets(chain_family, lower(address));
create index if not exists legacy_collectibles_chain_idx on legacy_collectibles(chain_id, lower(contract_address), token_id);
