export { SupportClient } from "./client.js";
export type {
  CreateTicketInput,
  IdentifySupportVisitorInput,
  ListMessagesInput,
  ListTicketsInput,
  MarkTicketReadInput,
  MessagePage,
  MessageAuthor,
  SendMessageInput,
  SupportAttachment,
  SupportContext,
  SupportEvent,
  SupportEventPage,
  SupportIdentity,
  SupportMessage,
  SupportLocale,
  SupportSession,
  SupportTicket,
  TicketPage,
  TicketPriority,
  TicketStatus,
  WatchTicketOptions,
  WidgetConfiguration,
  WidgetPosition,
} from "./types.js";
