'use client';
import { useState } from 'react';
import { Activity, AlertTriangle, ArrowRight, Check, CircleDot, Clock3, Gauge, Radio, RefreshCw, ShieldAlert, Sparkles, Users, X } from 'lucide-react';
import { detectDuplicatePass, detectGateCongestion, detectSpeakerReadiness } from '@/policies/detectors';
import type { AuditEntry, Gate, Incident, Session } from '@/lib/types';

const normalGates: Gate[] = [
  { gateId:'gate-main', name:'Main Entrance', rate:18, capacity:25, wait:2, status:'healthy' },
  { gateId:'gate-vip', name:'VIP / Speakers', rate:4, capacity:15, wait:1, status:'healthy' },
  { gateId:'gate-secondary', name:'Secondary Entrance', rate:7, capacity:30, wait:1, status:'healthy' },
];
const baseSession: Session = { sessionId:'session-main', title:'Programmable trust in the real world', room:'Main Stage', startsIn:42, occupancy:428, capacity:600, speaker:'Dr. Maya Torres', speakerReady:true };

export function LiveOpsConsole({ simulatorOpen = false }: { simulatorOpen?: boolean }) {
  const [gates,setGates]=useState(normalGates); const [sessions,setSessions]=useState([baseSession]); const [incidents,setIncidents]=useState<Incident[]>([]); const [audit,setAudit]=useState<AuditEntry[]>([{id:'boot',at:1788678000000,actor:'Simulator',action:'DEMO RESET',detail:'Seed 20260906 · synthetic event state'}]); const [selected,setSelected]=useState<string>(); const [pulse,setPulse]=useState(0);
  const active = incidents.filter(i=>!['resolved','rejected'].includes(i.status)); const selectedIncident = incidents.find(i=>i.id===selected) ?? incidents[0];
  const totalRate=gates.reduce((sum,g)=>sum+g.rate,0); const metrics=[['Check-ins / min',totalRate,'live'],['Active attendees','1,284','synthetic count'],['Active incidents',active.length,String(incidents.length)+' detected'],['High severity',active.filter(i=>i.severity==='high'||i.severity==='critical').length,'needs attention'],['Open recommendations',incidents.filter(i=>i.recommendation.status==='pending').length,'approval mode'],['Avg detection','—','measurement pending']];
  const pushIncident=(incident:Incident|null,action:string)=>{if(!incident)return;setIncidents(prev=>[incident,...prev.filter(i=>i.type!==incident.type)]);setSelected(incident.id);setAudit(prev=>[{id:incident.id,at:Date.now(),actor:'LiveOps policy',action,detail:'Incident created from deterministic evidence'},...prev]);setPulse(p=>p+1)};
  const surge=()=>{const next=gates.map(g=>g.gateId==='gate-main'?{...g,rate:68,wait:14,status:'congested' as const}:g);setGates(next);pushIncident(detectGateCongestion(next[0],next.slice(1)),'GATE CONGESTION DETECTED')};
  const duplicate=()=>pushIncident(detectDuplicatePass({passHash:'sha256:7ad78a-synthetic-4e92b1',gateId:'Main Entrance',at:Date.now()-32000},{passHash:'sha256:7ad78a-synthetic-4e92b1',gateId:'Secondary Entrance',at:Date.now()}),'DUPLICATE PASS DETECTED');
  const speaker=()=>{const next={...baseSession,startsIn:18,speakerReady:false};setSessions([next]);pushIncident(detectSpeakerReadiness(next),'SPEAKER READINESS DETECTED')};
  const reset=()=>{setGates(normalGates);setSessions([baseSession]);setIncidents([]);setSelected(undefined);setAudit([{id:String(Date.now()),at:Date.now(),actor:'Simulator',action:'DEMO RESET',detail:'Seed 20260906 · all data is synthetic'}]);setPulse(p=>p+1)};
  const decide=(decision:'approved'|'rejected')=>{if(!selectedIncident)return;setIncidents(prev=>prev.map(i=>i.id!==selectedIncident.id?i:{...i,status:decision==='approved'?(i.type==='GATE_CONGESTION'?'resolved':'actioned'):'rejected',recommendation:{...i.recommendation,status:decision}}));if(decision==='approved'&&selectedIncident.type==='GATE_CONGESTION')setGates(gates.map(g=>g.gateId==='gate-main'?{...g,rate:28,wait:4,status:'healthy'}:g.gateId==='gate-secondary'?{...g,rate:22,wait:3,status:'healthy'}:g));setAudit(prev=>[{id:String(Date.now()),at:Date.now(),actor:'Demo operator',action:`RECOMMENDATION ${decision.toUpperCase()}`,detail:selectedIncident.recommendation.summary},...prev]);setPulse(p=>p+1)};
  const fullDemo=()=>{reset();setTimeout(surge,250);setTimeout(duplicate,500);setTimeout(speaker,750)};
  return <main>
    <header><div className="brand"><div className="mark">H</div><div><b>HASHPASS</b><span>LIVEOPS</span></div></div><nav><a className="active" href="/live">LIVE</a><a href="#incidents">INCIDENTS</a><a href="/simulator">SIMULATOR</a><a href="#audit">AUDIT</a></nav><div className="connection"><i/><span>OPERATIONAL PLANE</span><b>LIVE</b></div></header>
    <section className="hero"><div><div className="eyebrow"><Radio size={14}/> BSL BOGOTÁ 2026 DEMO <span>SIMULATED</span></div><h1>Realtime event operations.<br/><em>Before problems become incidents.</em></h1><p>SENSE <ArrowRight/> DETECT <ArrowRight/> REASON <ArrowRight/> PROPOSE <ArrowRight/> APPROVE <ArrowRight/> ACT <ArrowRight/> VERIFY</p></div><div className="heroActions"><button className="secondary" onClick={reset}><RefreshCw/> Reset</button><button className="primary" onClick={fullDemo}><Sparkles/> Run full demo</button></div></section>
    <section className="metrics">{metrics.map(([label,value,note],i)=><article key={label} className={i===3&&Number(value)>0?'dangerMetric':''}><span>{label}</span><strong key={`${pulse}-${label}`}>{value}</strong><small>{i===0&&<i className="liveDot"/>}{note}</small></article>)}</section>
    <div className="workspace"><div className="mainColumn">
      <section className="panel"><div className="panelTitle"><div><h2>Entrance flow</h2><p>Throughput and queue pressure across active gates</p></div><span className="updated"><Activity/> REACTIVE</span></div><div className="gateHead"><span>GATE</span><span>SCANS / MIN</span><span>UTILIZATION</span><span>EST. WAIT</span><span>STATUS</span></div>{gates.map(g=><div className={`gateRow ${g.status}`} key={g.gateId}><div><b>{g.name}</b><small>{g.capacity} nominal/min</small></div><strong>{g.rate}</strong><div className="util"><div><i style={{width:`${Math.min(100,g.rate/g.capacity*100)}%`}}/></div><span>{Math.round(g.rate/g.capacity*100)}%</span></div><b>{g.wait} min</b><label>{g.status}</label></div>)}</section>
      <section className="panel sessions"><div className="panelTitle"><div><h2>Session readiness</h2><p>Rooms, occupancy, and speaker operations</p></div></div>{sessions.map(s=><div className="session" key={s.sessionId}><div><small>{s.room.toUpperCase()}</small><b>{s.title}</b></div><div><small>START</small><b>{s.startsIn} min</b></div><div><small>OCCUPANCY</small><b>{s.occupancy} / {s.capacity}</b></div><div><small>SPEAKER</small><b className={s.speakerReady?'ready':'notReady'}>{s.speakerReady?<Check/>:<Clock3/>}{s.speakerReady?'Checked in':'Not checked in'}</b></div></div>)}</section>
      <section className="panel audit" id="audit"><div className="panelTitle"><div><h2>Operational audit</h2><p>Every detection and human decision is attributable</p></div></div>{audit.slice(0,5).map(a=><div className="auditRow" key={a.id}><CircleDot/><time>{new Date(a.at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'})}</time><div><b>{a.action}</b><span>{a.actor} · {a.detail}</span></div></div>)}</section>
    </div><aside className="sideColumn">
      <section className="panel simulator"><div className="panelTitle"><div><h2>{simulatorOpen?'Scenario control':'Signal simulator'}</h2><p>Deterministic · seed 20260906</p></div><span className="simBadge">SIM</span></div><button onClick={surge}><Gauge/> Gate surge <span>Hero</span></button><button onClick={duplicate}><ShieldAlert/> Duplicate pass</button><button onClick={speaker}><Clock3/> Speaker delay</button><small>Simulation events are isolated and marked <code>simulation=true</code>.</small></section>
      <section className="panel incidents" id="incidents"><div className="panelTitle"><div><h2>Incident feed</h2><p>{active.length} active · newest first</p></div></div>{incidents.length===0?<div className="empty"><Check/><b>Operations nominal</b><span>No active incidents. Trigger a scenario to see the control loop.</span></div>:incidents.map(i=><button onClick={()=>setSelected(i.id)} className={`incident ${selectedIncident?.id===i.id?'selected':''}`} key={i.id}><span className={`severity ${i.severity}`}>{i.severity}</span><b>{i.title}</b><small>{i.evidence[0]}</small><label>{i.status.replace('_',' ')}</label></button>)}</section>
    </aside></div>
    {selectedIncident&&<div className="drawer"><div className="drawerTop"><div><span className={`severity ${selectedIncident.severity}`}>{selectedIncident.severity}</span><small>{selectedIncident.type}</small></div><button aria-label="Close" onClick={()=>setSelected(undefined)}><X/></button></div><h2>{selectedIncident.title}</h2><p>{selectedIncident.summary}</p><h3>Evidence</h3><ul>{selectedIncident.evidence.map(e=><li key={e}><CircleDot/>{e}</li>)}</ul><div className="recommend"><span><Sparkles/> LIVEOPS RECOMMENDATION <i>POLICY FALLBACK</i></span><h3>{selectedIncident.recommendation.summary}</h3><p><b>Why LiveOps is recommending this</b><br/>{selectedIncident.recommendation.rationale}</p><p><b>Expected impact</b><br/>{selectedIncident.recommendation.impact}</p><div><label>RISK · {selectedIncident.recommendation.risk}</label><label>HUMAN APPROVAL REQUIRED</label></div></div>{selectedIncident.recommendation.status==='pending'?<div className="decisions"><button onClick={()=>decide('rejected')}><X/> Reject</button><button onClick={()=>decide('approved')}><Check/> Approve action</button></div>:<div className={`decisionDone ${selectedIncident.recommendation.status}`}><Check/> Recommendation {selectedIncident.recommendation.status}; action recorded in audit log.</div>}</div>}
  </main>;
}
