import React from 'react';
import {AbsoluteFill, Easing, interpolate, Sequence, useCurrentFrame} from 'remotion';
import {openProofContent as c} from '../../../../packages/config/src/openproof-content';
const scenes=[
 {start:0,dur:210,kicker:'OPENPROOF',title:'Attendance should outlive the platform.',body:'A credential is only useful if it survives the platform that issued it.'},
 {start:210,dur:270,kicker:'THE SILO PROBLEM',title:'Today, attendance lives in silos.',body:'Private databases disconnect attendees, organizers and partners.'},
 {start:480,dur:330,kicker:'HASH PASS × ARKIV',title:'One shared attendance schema.',body:'Event · AttendanceClaim · CheckInReceipt · CrossAppAttestation'},
 {start:810,dur:390,kicker:'ISSUANCE FLOW',title:'Verify. Issue. Transfer control.',body:'Organizer → QR check-in → HashPass verification → AttendanceClaim → attendee wallet'},
 {start:1200,dur:360,kicker:'ARKIV PRIMITIVES',title:'Queryable. Time-scoped. Owned.',body:'$creator proves the issuer. $owner proves who controls the credential.'},
 {start:1560,dur:330,kicker:'CROSS-APP VERIFICATION',title:'Verified attendance.',body:'Issuer verified · Credential active · No dependency on the HashPass private API'},
 {start:1890,dur:210,kicker:'PRIVACY BOUNDARY',title:'Personal data stays private.',body:'Arkiv stores only public proof hashes, pseudonymous IDs and credential metadata.'},
 {start:2100,dur:150,kicker:'OPENPROOF',title:'Portable attendance for every event.',body:'Attendance should outlive the platform.'},
] as const;
export const OpenProof:React.FC=()=> <AbsoluteFill style={{background:'#050812',color:'#f7f9ff',fontFamily:'Arial, sans-serif'}}>{scenes.map((s,i)=><Sequence key={s.title} from={s.start} durationInFrames={s.dur}><Scene index={i} {...s}/></Sequence>)}</AbsoluteFill>;
function Scene({index,dur,kicker,title,body}:{index:number;dur:number;kicker:string;title:string;body:string}){const f=useCurrentFrame();const enter=interpolate(f,[0,24],[0,1],{extrapolateRight:'clamp',easing:Easing.out(Easing.cubic)});const fade=index===7?interpolate(f,[dur-25,dur],[1,0],{extrapolateLeft:'clamp'}):1;return <AbsoluteFill style={{opacity:fade,padding:'100px 120px',display:'flex',flexDirection:'column',justifyContent:'space-between',overflow:'hidden'}}><div style={{position:'absolute',inset:0,background:'radial-gradient(circle at 80% 20%,#8b7cff20,transparent 38%),linear-gradient(#ffffff07 1px,transparent 1px),linear-gradient(90deg,#ffffff07 1px,transparent 1px)',backgroundSize:'auto,64px 64px,64px 64px'}}/><div style={{position:'relative',transform:`translateY(${(1-enter)*35}px)`,opacity:enter}}><div style={{fontFamily:'monospace',fontSize:22,letterSpacing:5,color:'#4dd8ff',marginBottom:42}}>{String(index+1).padStart(2,'0')} / {kicker}</div><div style={{fontSize:index===0||index===7?106:86,fontWeight:700,lineHeight:1.02,letterSpacing:-4,maxWidth:1450}}>{title}</div><div style={{fontSize:31,lineHeight:1.5,color:'#aeb9cb',maxWidth:1380,marginTop:38}}>{body}</div></div><Visual index={index} progress={enter}/><div style={{position:'relative',display:'flex',justifyContent:'space-between',alignItems:'end'}}><div style={{fontSize:24,color:'#d7deeb',background:'#0b1120e8',border:'1px solid #ffffff24',borderRadius:12,padding:'15px 22px',maxWidth:1500}}>{c.voiceover[index]}</div><div style={{fontFamily:'monospace',fontSize:18,color:'#768399'}}>ARKIV IDEATHON</div></div></AbsoluteFill>}
function Visual({index,progress}:{index:number;progress:number}){const labels=index===1?['EVENT PLATFORM A','EVENT PLATFORM B','EVENT PLATFORM C']:index===2?c.entities.map(x=>x.name):index===3?['ORGANIZER','QR CHECK-IN','HASHPASS','CLAIM','WALLET']:index===4?['QUERYABLE','TIME-SCOPED','$creator','$owner']:index===5?['OPEN CAMPUS','→ ARKIV QUERY →','✓ VERIFIED']:index===6?['PRIVATE: names · emails · QR secrets','PUBLIC: proof hash · issuer · expiry']:[];if(!labels.length)return <div style={{position:'relative',height:220,border:'1px solid #8b7cff55',borderRadius:22,background:'#111326',transform:`scale(${.96+.04*progress})`,display:'grid',placeItems:'center',fontFamily:'monospace',fontSize:26,color:'#68e0ad'}}>claim-chile-ana-001 · VERIFIED · 5 YEARS</div>;return <div style={{position:'relative',display:'flex',gap:18,alignItems:'stretch',height:220}}>{labels.map((x,i)=><div key={x} style={{flex:1,border:`1px solid ${i%2?'#8b7cff':'#4dd8ff'}77`,borderRadius:18,background:'#0b1220',display:'grid',placeItems:'center',textAlign:'center',padding:22,fontFamily:'monospace',fontSize:23,transform:`translateY(${(1-progress)*(20+i*7)}px)`,opacity:progress}}>{x}</div>)}</div>}
