export type CollectibleSource = 'hashpass_moment' | 'legacy_poap';
export type ChainFamily = 'algorand' | 'evm' | 'offchain';
export type AttendanceRole = 'attendee' | 'speaker' | 'organizer' | 'sponsor' | 'volunteer';
export type AttendanceVerificationMethod = 'hashpass_check_in' | 'authorized_scan_log' | 'pass_consumed_checkpoint' | 'verified_event_role' | 'organizer_approved' | 'imported_authoritative_list';
export type ClaimState = 'not_eligible' | 'eligible' | 'claimable' | 'claimed_in_hashpass' | 'claimable_onchain' | 'onchain_pending' | 'minted_onchain' | 'transferred_to_user_wallet' | 'expired' | 'revoked' | 'failed' | 'duplicate_prevented';
export interface MomentEventMetadata { id: string; name: string; edition: string; country: string; city: string; venue?: string; startsAt: string; endsAt: string; }
export interface MomentMetadata { schema: 'hashpass-moment-v1'; name: string; description: string; type: 'proof_of_attendance'; event: MomentEventMetadata; issuer: { name: string; eventOrganizer: string }; holder: { subject: string; role: AttendanceRole }; attendance: { status: 'verified'; method: AttendanceVerificationMethod; verifiedAt: string }; artwork: { image: string; hash?: string }; proof: { digest: string; verificationUrl: string }; onchain: { status: ClaimState; network: 'algorand'; standard: 'ARC-72'; tokenId: string | null; ownerAddress: string | null; transactionId: string | null }; traits?: Record<string, string | number | boolean>; metadataVersion: 1; sourceSystem: 'hashpass'; }
export interface AttendanceCredential { id: string; eventId: string; userId: string; role: AttendanceRole; attendanceStatus: 'verified' | 'revoked' | 'pending'; verificationMethod: AttendanceVerificationMethod; verificationReference?: string; verifiedBy?: string; verifiedAt: string; metadata?: Record<string, unknown>; }
export interface Collection { id: string; eventId: string; source: CollectibleSource; name: string; description: string; artworkUri: string; issuerName: string; claimStart?: string; claimEnd?: string; status: 'draft' | 'published' | 'paused' | 'archived'; metadata?: Record<string, unknown>; }
export interface CollectibleItem { id: string; collectionId: string; userId: string; sourceIdentifier: string; proofDigest: string; metadata: MomentMetadata; claimState: ClaimState; createdAt: string; }
export interface ClaimRequest { eventId: string; collectionId: string; userId: string; idempotencyKey: string; now?: string; claimChannel?: 'wallet' | 'admin' | 'api'; }
export interface ClaimResult { state: ClaimState; item?: CollectibleItem; duplicate: boolean; reason?: string; }
export interface VerificationResponse { valid: boolean; type: 'proof_of_attendance'; issuer: string; event: { id: string; name: string }; holder: { subject: string }; attendance: { verified: boolean; method: AttendanceVerificationMethod }; onchain: { status: string; network: string; standard: string; tokenId: string | null; transactionId: string | null }; proofDigest: string; verifiedAt: string; }
