'use client';
import {useState} from 'react';
import {openProofContent as c} from '@hashpass/config/openproof';
import styles from './openproof.module.css';

const flow=[['Organizer','Verifies attendance'],['QR check-in','Temporary evidence'],['HashPass','Private verification'],['AttendanceClaim','$creator · $owner'],['Arkiv','Public query layer'],['Attendee wallet','Controls credential'],['Independent app','Queries & verifies']];
const publicData=['Public event metadata','Pseudonymous identifiers','Signed claims','Proof hashes','Issuer and ownership metadata','Expiry and status fields'];
const privateData=['Names','Emails','Phone numbers','Raw QR codes','Anti-replay secrets','Device and location details','Fraud scores','Private networking data','Organizer notes'];
export function OpenProofExperience(){const [query,setQuery]=useState(0);return <main className={styles.page}>
  <nav className={styles.nav}><img src="/logo-full-hashpass-white.svg" alt="HashPass"/><span>OpenProof <b>× Arkiv</b></span><a href="#model">Data model</a></nav>
  <section className={`${styles.hero} ${styles.wrap}`}><div><p className={styles.eyebrow}>ARKIV IDEATHON · CONCEPT DEMONSTRATION</p><h1>Attendance should <em>outlive</em> the platform.</h1><p className={styles.lead}>HashPass OpenProof is an interoperable attendance passport built on Arkiv. Event organizers issue verifiable claims, attendees control them, and compatible applications can query them without depending on one centralized database.</p><div className={styles.actions}><a href="#model">Explore the OpenProof model</a><a href="#walkthrough">Watch the 75-second walkthrough</a></div><small>Concept demonstration — not a live credential registry.</small></div><Passport/></section>
  <Section eyebrow="THE PROBLEM" title="Event history should not disappear with a platform."><div className={styles.three}>{['Attendees lose access to their participation history.','Organizers cannot easily verify credentials from other platforms.','Sponsors and partners cannot query trusted attendance without contacting every issuer.'].map((x,i)=><article className={styles.card} key={x}><span>0{i+1}</span><h3>{x}</h3><p>Isolated platform <b>×</b> portable proof</p></article>)}</div></Section>
  <Section eyebrow="THE OPENPROOF SOLUTION" title="A shared attendance layer for every event platform."><Diagram/></Section>
  <Section id="model" eyebrow="INTERACTIVE ARKIV DATA MODEL" title="The data model is the product."><p className={styles.intro}>Expand each entity to see what it carries, who controls it and how long it exists.</p><div className={styles.entities}>{c.entities.map(e=><details className={`${styles.entity} ${styles[e.tone]}`} key={e.name}><summary><span>{e.name}</span><i>+</i></summary><p>{e.detail}</p><div>{e.attributes.map(a=><code key={a}>{a}</code>)}</div></details>)}</div></Section>
  <Section eyebrow="LOCAL QUERY SIMULATOR" title="Ask the attendance graph."><div className={styles.explorer}><div className={styles.queryTabs}>{c.queries.map((q,i)=><button aria-pressed={i===query} onClick={()=>setQuery(i)} key={q.label}><span>0{i+1}</span>{q.label}</button>)}</div><div className={styles.results}><p>ARKIV-STYLE FILTER</p><code>{c.queries[query].filter}</code><div className={styles.resultList}>{c.queries[query].rows.map(r=><div key={r[0]}><span>{r[0]}</span><b>{r[1]}</b></div>)}</div><small>Numeric timestamps enable range queries. Shared eventId and claimId keys connect related entities.</small></div></div></Section>
  <Section eyebrow="EXPIRY + OWNERSHIP" title="Credentials have a lifecycle."><div className={styles.timeline}>{['Check-in receipt','7-day verification','Attendance claim','90-day cross-app use','Explicit extension'].map((x,i)=><div key={x}><span>{i+1}</span><b>{x}</b></div>)}</div><div className={styles.ownership}><p><code>$creator</code> proves who issued the claim.</p><p><code>$owner</code> proves who controls it.</p><p>Long-term claims last {c.lifetimes.claimYears} years and can be explicitly extended.</p></div></Section>
  <Section eyebrow="PRIVACY BOUNDARY" title="Public verification does not require public personal data."><div className={styles.privacy}><List title="Stored on Arkiv" items={publicData}/><List title="Kept privately by HashPass" items={privateData}/></div></Section>
  <Section eyebrow="THE COUNTERFACTUAL" title="Why not a plain database?"><div className={styles.four}>{[['Queryable','Attendance records are indexed and filterable.'],['Time-scoped','Evidence expires by design.'],['Tamper-proof provenance','$creator makes the issuer independently verifiable.'],['Wallet-controlled ownership','$owner lets the attendee control the credential.']].map(x=><article className={styles.card} key={x[0]}><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div><blockquote>Without Arkiv, OpenProof becomes another private attendance database or closed collectible platform. With Arkiv, compatible event applications verify the same public credential layer without depending on HashPass’s private API.</blockquote></Section>
  <section id="walkthrough" className={`${styles.final} ${styles.wrap}`}><p className={styles.eyebrow}>AN OPEN STANDARD, NOT AN NFT COLLECTION</p><h2>Build an open attendance layer.</h2><p>HashPass OpenProof starts with event infrastructure in Chile and Colombia, but the schema is designed for any compatible event platform.</p><div className={styles.actions}><a href="#model">View the data model</a><a href="/openproof/openproof-walkthrough.mp4">Watch the walkthrough</a><a href="/">Explore HashPass</a></div><small>Designed for the Arkiv Ideathon — concept demonstration.</small></section>
 </main>}
function Section({eyebrow,title,children,id}:{eyebrow:string,title:string,children:React.ReactNode,id?:string}){return <section id={id} className={`${styles.section} ${styles.wrap}`}><p className={styles.eyebrow}>{eyebrow}</p><h2>{title}</h2>{children}</section>}
function Passport(){return <article className={styles.passport}><header><span>OPENPROOF / PASSPORT</span><b>● VERIFIED</b></header><h2>wallet:demo-ana</h2><p>Owned by attendee · synthetic profile</p>{['Blockchain Summit Latam Chile 2026','Blockchain Summit Latam Colombia 2026','Open Web3 Builders Meetup'].map((x,i)=><div className={styles.credential} key={x}><i>{i+1}</i><span><b>{x}</b><small>Issued by verified organizer</small></span><strong>{i===2?'EXPIRY SOON':'5 YEARS'}</strong></div>)}</article>}
function Diagram(){return <div className={styles.diagram} role="img" aria-label="Organizer QR check-in flows through HashPass verification into an Arkiv AttendanceClaim owned by an attendee wallet and queried by an independent verifier">{flow.map((n,i)=><div className={styles.node} tabIndex={0} key={n[0]}><span>{String(i+1).padStart(2,'0')}</span><b>{n[0]}</b><small>{n[1]}</small><aside>Entity: {i<3?'CheckInReceipt':'AttendanceClaim'}<br/>Creator: verified organizer<br/>Owner: attendee wallet<br/>Query: eventId = “{c.eventId}”</aside></div>)}</div>}
function List({title,items}:{title:string,items:string[]}){return <article><h3>{title}</h3>{items.map(x=><p key={x}>✓ {x}</p>)}</article>}
